import { NextResponse } from 'next/server';
import { ttsEngine } from '@/lib/engine/tts';

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { text, voiceId, provider, language, speed } = body || {};

    const sampleText = text || 'Hello! This is a voice preview generated by Clipped AI Studio.';
    const result = await ttsEngine.synthesize({
      text: sampleText,
      voiceId,
      voice: voiceId,
      provider: provider || 'auto',
      language: language || 'en-US',
      speed: speed || 1.0,
    });

    return NextResponse.json({
      success: true,
      audioUrl: result.audioUrl,
      audioBase64: result.audioBase64,
      duration: result.duration,
      providerUsed: result.providerUsed,
      voiceId: result.voiceId,
    });
  } catch (error: any) {
    console.error('[TTS Preview API] Error:', error);
    return NextResponse.json(
      { success: false, error: error.message || 'Failed to generate voice preview' },
      { status: 500 }
    );
  }
}
